before:
  hooks:
    - make clean
    - make deps
    - make gen-ui
    - make build-ui
    - make gen-go
    - make test
builds:
- env:
  - CGO_ENABLED=0
  flags:
  - -tags=release
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brew:
  github:
    owner: stratumn
    name: homebrew-groundcontrol
